name: TIM
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - joblib=1.2.0
  - numpy=1.24
  - pandas=2.0.3
  - pip=23.3
  - python=3.8.18
  - pytorch=1.11.0
  - setuptools=68.0.0
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - pip:
      - fvcore==0.1.5.post20220305
      - iopath==0.1.9
      - psutil==5.9.0
      - pytorch-warmup==0.1.1
      - simplejson==3.17.6
      - wandb==0.12.11
